name: My New Workflow
run-name: My New Workflow
permissions:
  contents: write
'on':
  push: {}
jobs:
  main-job:
    name: Main Job
    runs-on:
    - ubuntu-latest
    needs: []
    steps:
    - name: Super Linter
      uses: super-linter/super-linter@v7.1.0
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.6.8
      with:
        folder: hi
