name: New workflow
run-name: New workflow Runname
permissions: {}
'on':
  push: {}
jobs:
  main-job:
    name: Main Job
    runs-on:
    - ubuntu-latest
    needs: []
    steps:
    - name: Run Code
      run: echo hi
