name: Run Tests
run-name: Run Tests
permissions: {}
'on':
  pull_request:
    branches:
    - main
jobs:
  run-tests:
    name: Run Tests
    runs-on:
    - ubuntu-latest
    needs: []
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.0
    - name: Run Tests
      run: npm run test
