name: New workflow
run-name: New workflow Runname
permissions:
  contents: write
'on':
  push: {}
jobs:
  main-job:
    name: Main Job
    runs-on:
    - ubuntu-latest
    needs: []
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.0
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.6.8
      with:
        folder: dist
