name: New workflow
run-name: New workflow Runname
permissions: {}
'on':
  push: {}
jobs:
  main-job:
    name: Main Job
    runs-on:
    - ubuntu-latest
    needs: []
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.0
    - name: Run Code
      run: npm ci && npm run build
